# Generated by Django 5.2.3 on 2025-06-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securegate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
