# Generated by Django 5.2.3 on 2025-06-15 05:47

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securegate', '0002_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
