# Generated by Django 5.2.3 on 2025-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegate', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-active_at'], 'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(default=123, help_text="Telegram's unique user ID", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='active_at',
            field=models.DateTimeField(auto_now=True, help_text='Last interaction timestamp'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(help_text="User's first name (max 50 characters)", max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name (max 50 characters, optional)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(help_text='Unique Telegram username (@handle, max 50 chars)', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='securegate__usernam_f97972_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id'], name='securegate__telegra_eddf27_idx'),
        ),
    ]
