# Generated by Django 5.2.3 on 2025-06-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegate', '0004_alter_telegramuser_options_remove_telegramuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, help_text='Unique Telegram username (@handle, max 50 chars)', max_length=50, null=True, unique=True),
        ),
    ]
